apiVersion: v1
kind: Pod
metadata:
  labels:
    app: visidata
  namespace: default
spec:
  containers:
  - image: localhost:31500/vdwww/vdwww:latest
    imagePullPolicy: Always
    name: app
    ports:
    - containerPort: 9000
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    volumeMounts:
    - mountPath: /app/data
      mountPropagation: None
      name: data
      readOnly: true
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: do-spaces-vdata
