# Note that Github's web editor has linting for Github Action YAML
# And also there is a JSON schema for validating in your local editor:
# http://json.schemastore.org/github-workflow

name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VD_ENV: "test"
      GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: vdwww
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: .github/workflows/build.sh
    - name: Run tests
      run: .github/workflows/test.sh
    - name: Upload screenshots
      run: .github/workflows/on_failure.sh
      if: failure()
    - name: Deploy
      run: .github/workflows/deploy.sh
