# Note that Github's web editor has linting for Github Action YAML
# And also there is a JSON schema for validating in your local editor:
# http://json.schemastore.org/github-workflow

name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: .github/workflows/build.sh
    - name: Run tests
      run: .github/workflows/test.sh
    - name: Deploy
      env:
        GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
        VD_ENV: "test"
      run: .github/workflows/deploy.sh
