name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Github Docker Registry
      env:
        GITCRYPT_KEY: {{ secrets.GITCRYPT_KEY }}
      run: .github/workflows/build_and_push.sh
